# gCV-Bridge config
# =================

# Discord bot settings
discord:
  # The bot token, used to log into Discord.
  token: ""
  # URLs of webhooks for the bot to send messages to (should be done per-channel)
  # You can specify multiple channels here by separating the IDs with a comma.
  out-webhooks: []
  # The IDs of the channels to receive messages from (must be a server text channel).
  # You can specify multiple channels here by separating the IDs with a comma.
  in-channels: []
  # The IDs of the channels to send messages to (must be a server text channel).
  # You can specify multiple channels here by separating the IDs with a comma.
  out-channels: []
  # Settings for the playerlist command
  playerlist:
    # Whether to enable the playerlist command.
    # This will only work in channels listed under the in-channels section above.
    enabled: true
    # The format for the playerlist command.
    format: "**{count} players online:** ```\n{players}\n```"
    # The separator between each player name in the player list.
    separator: ", "
    # How long in seconds to wait before removing the original command message.
    # Set to 0 for instant, -1 for never.
    command-remove-delay: 0
    # How long in seconds to wait before removing the bot's response message.
    # Set to 0 for instant, -1 for never.
    response-remove-delay: 10


# Velocity settings
velocity:
  # The format of the message sent to Discord when a player connects.
  # Supported placeholders: {player}
  join-format: "**{player} joined the game**"
  # The format of the message sent to Discord when a player disconnects.
  quit-format: "**{player} left the game**"
  # Whether or not a player needs the "gcvb.see" permission to see incoming messages from Discord.
  require-see-permission: false
  # Whether or not players need the "gcvb.send" permission for their messages to be sent to Discord.
  require-send-permission: false


# gChat integration settings
gchat:
  # The name of the default gChat format to use for incoming messages from Discord.
  # This should be defined in the gChat config.yml, then the name set below.
  # You can create a format just for Discord if you want.
  default-format: default
  # A list of key-value pairs of formats to use for specific channel IDs
  # These IDs should correspond to one of the IDs in `in-channels`
  # If a channel is not specified here, it will use the default format
  # This list can be left empty if no per-channel formats are used
  channel-formats:
    channel1-id: default
    channel2-id: default
  # possible placeholders for from-discord messages
  #   {name} = username of sender
  #   {display_name} = display name of sender
  #   {message} = message content
  #   {channel} = channel name message was sent in

# Neutron integration settings
neutron:
  # The format for sending Neutron /alert messages to Discord.
  # Use {message} for the message and {author} for the sender's name.
  # Leave blank ("") to disable sending alerts to Discord.
  alert-format: "**BROADCAST** {message}"